- name: Run Tests
  env: 
    MONGO_DB_PW: ${{ secrets.MONGO_DB_PW }}
on:
  push:
    branches:
      - featuer/workflows
  
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"